heat_template_version: 2014-10-16

description: >
  Extra hostname configuration

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: ssh_config}

ssh_config:
  type: OS::Heat::SoftwareConfig
  properties:
    config: |
      #!/bin/bash
      if [[ `hostname` = *"sds"* ]]
      then
        multipath -F
        systemctl stop multipathd
        rm /etc/multipath.conf
      fi

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
